--CREATE DATABASE  IF NOT EXISTS 'TEST_DB';
--USE 'TEST_DB';
DROP TABLE IF EXISTS MESSAGES;
CREATE TABLE MESSAGES(
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `message` varchar(200) NOT NULL,
  PRIMARY KEY (`id`)
);


INSERT INTO MESSAGES VALUES (1,'Hello World');

